ignore:
  - "src/index.js"
  - "e2e"
  - "src/RouteManager/UpdateRoute.js"
  - "src/caches/fileCache/FileCache.js"
  - "src/components/pages/NotificationsPage.js"
  - "src/NotificationManager/NotificationManager.js"
  - "src/util/PermissionManager.js"
  - "src/util/LdflexHelper.js"
  - "src/ShareManager/RetrieveRoute.js"
  - "src/ShareManager/ShareRoute.js"
  - "src/RouteManager/UpdateRoute.js"
  - "src/RouteManager/DeleteUserRoute.js"
  - "src/FriendManager/AddFriend.js"
  - "src/FriendManager/DeleteFriend.js"
  - "src/FriendGroupManager/GetFriendGroup.js"
  - "src/fileRelatedTests/"
  - "src/components/generic_components/List.js"
  - "src/components/map_components/MapContainer.js"
  - "src/components/map_components/MapRoute.js"
  - "src/CommentsManager/AddComment.js"
  - "src/CommentsManager/CreateCommentsFile.js"
  - "src/CommentsManager/GetComments.js"
  - "src/data-access/FileManager/GPXparser.js";
  - "src/data-access/FileManager/RouteUpload.js";
  - "src/data-access/FileManager/FolderCreator";
  - "src/data-access/UserData.js";