ignore:
  - "src/index.js"
  - "e2e"
  - "src/RouteManager/UpdateRoute.js"
  - "src/caches/fileCache/FileCache.js"
  - "src/components/pages/NotificationsPage.js"
  - "src/NotificationManager/NotificationManager.js"
  - "src/util/PermissionManager.js"
  - "src/util/LdflexHelper.js"
  - "src/ShareManager/RetrieveRoute.js"
  - "src/ShareManager/ShareRoute.js"
  - "src/RouteManager/UpdateRoute.js"
  - "src/RouteManager/DeleteUserRoute.js"
  - "src/FriendManager/AddFriend.js"
  - "src/FriendManager/DeleteFriend.js"
  - "src/FriendGroupManage/GetFriendGroup.js"
  - "src/fileRelatedTests/"
